### ISSUE TITLE
SimpleTokenize does not accept startPos and endPos

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/salt#105]
Unlike the TreeTagger tokenizer, the SimpleTokenizer does not allow setting a character offset for the portion of an SText that we want to tokenize. It feeds null arguments to the tokenize() method:

https://github.com/korpling/salt/blob/develop/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/SimpleTokenizer.java#L61

This is causing the different behavior of the two tokenizers in the RSTImporter, and prevents fixing the bug in korpling/pepperModules-RSTModules#2 . It should be possible to specify the start and end offsets (the default can stay null, which makes the tokenizer treat the whole text).

@thomaskrause : this is the function that requires changing in order to ensure a specific tokenization based on spaces for merging purposes - then we can fully auto-merge corpora like GUM.

**Comment by thomaskrause** [comment]
Can't you call the public tokenize method with the start and end offset parameters directly in the RSTModules?

https://github.com/korpling/salt/blob/develop/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/SimpleTokenizer.java#L77

**Comment by thomaskrause** [comment]
What I meant was if the RST2SaltMapper could instead of callig
```
tokenizer.tokenize(sText, seps);
```
in https://github.com/korpling/pepperModules-RSTModules/blob/master/src/main/java/org/corpus_tools/peppermodules/rstModules/RST2SaltMapper.java#L240 
could call 

```
tokenizer.tokenize(sText, start, end, seps);
```

**Comment by amir-zeldes** [comment]
Yes, sorry, I think I had a brain meltdown there for a moment. However, this sadly doesn't solve the problem due to what I think is a bug in tokenize(sText, start, end, seps):

If you set the start and end positions, they get used in order to snip the correct amount of text from the textualDS:

```
text = textualDS.getText().substring(startPos, endPos).toCharArray();
```

However sadly, later the variable currStart is set to 0, and the offset from startPos is not added:

```
			int currStart = 0; // current start position for token
			int currEnd = 0; // current end position for token
			boolean wasHere = false;
			for (char chr : text) {
				wasHere = false;
				for (char sep : separator) {
					if (chr == sep) {
						if (currStart != currEnd) {
							// create token
							getDocumentGraph().createToken(textualDS, currStart, currEnd);
```

I think the last line should read:

```
getDocumentGraph().createToken(textualDS, startPos + currStart, startPos + currEnd);
```

And similarly here:

```
			if (!isSep) {
				// create a token for the last part of text, if last character
				// was not a separator
				getDocumentGraph().createToken(textualDS, currStart, currEnd);
			}
```

Does that make sense?

**Comment by amir-zeldes** [comment]
Moving this to a new issue #108
