### ISSUE TITLE
enhance SaltFactory

### ISSUE THREAD

**Issue by MartinKl** [korpling/salt#11]
enhance SaltFactory with functionality of DOTResource
add the following methods to SaltFactory:

    * private void saveSCorpusGraph(SCorpusGraph sCorpusGraph, URI uri)
    * private void saveSDocumentGraph(SDocumentGraph sDocumentGraph, URI uri)

and the JavaDoc of DOTResource

**Comment by FlorianZipser** [comment]
done with Salt 3.0 see SaltUtil.saveCorpusGraph_DOT(SCorpusGraph corpusGraph, URI location)
