### ISSUE TITLE
SaltStatistics

### ISSUE THREAD

**Issue by MartinKl** [korpling/salt#30]
Enhance the salt project saltCommon for the mechanism of a simple statistical evaluation. The statistical evaluation consists of giving the number of nodes, relations, annotations concerning to their type and so on.
The statistical evaluation shall be persist as an xml format following a predefined form. This task consists of several sub-tasks.

**Comment by FlorianZipser** [comment]
This was resolved by @korpling/pepperModules-SaltInfoModules.
