### ISSUE TITLE
Remove HashEList creation in equals()

### ISSUE THREAD

**Issue by MartinKl** [korpling/salt#46]
Location: branch salt-equals, revision 2615
```
salt-graph:
      LabelableElementImp
      GraphImp
```
equality check for labels, edges and nodes should use contains( ) HashEList.
Thus, the EList, which contains the Labels/Nodes/Edges, should be a HashEList.

See TODOs

**Comment by FlorianZipser** [comment]
Done by new Salt implementation. See Salt 3.x.
