### ISSUE TITLE
Tokenizer sets Italian (?) clitics to LanguageCode for Spanish

### ISSUE THREAD

**Issue by sdruskat** [korpling/salt#86]
Cf. https://github.com/korpling/salt/blob/3fe7e613a9ff52a00e57b33cef2a17da6a724f95/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java#L333-L334

I'm not a speaker of Italian, but I do know a little Spanish. I've never seen any of the clitics above in Spanish, but am sure I've seen at least some of them on menus in pizzerias :wink:.

**Comment by amir-zeldes** [comment]
Absolutely correct, that's Italian, not Spanish

**Comment by sdruskat** [comment]
I can fix this in the greater context of fixing the handling of clitics by the Tokenizer. Hopefully ready early next week.
